name: Release

on:
  push:
    branches:
      - main
      - development

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [webapp, cli]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Git config
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
      - name: Install dependencies
        run: bun install
      - name: Release
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          node scripts/run-release-it.js ${{ matrix.package }} --ci
